### ISSUE TITLE
iOS system introspection

### ISSUE THREAD

**Issue by lukasjuhrich** [calabash/DeviceAgent.iOS#307]
## Proposal
I propose to add an endpoint `/system-info`, `/sysinfo`, `/info` or similar, in order to provide the iOS version and perhaps other addintional system information.

## Motivation
There are differences in the document tree depending on the Version. For instance, from iOS 10 to 11, the table view hierarchy changed, so instead of waiting for an element of the class `UITableViewCellDeleteConfirmationView` to appear, the test must now use `UISwipeActionPullView`.
However, the test cannot change those strategies at runtime, which means I cannot use an ios10 test device anymore if I configured my CI to use an ios11 device.

**Comment by jmoody** [comment]
The Calabash iOS client and the Xamarin.UITest client have APIs for finding the form-factor and device versions.  Are you using a different client?

The `/device` route exists and will provide this information:

https://github.com/calabash/DeviceAgent.iOS/blob/develop/Server/Utilities/CBXDevice.m#L469

**Comment by lukasjuhrich** [comment]
Thanks for the quick reaction, the `/device` endpoint should do exactly what I need.
I also found the part of the Xamarin.UITest documentation I must have overlooked.
Have a great day!

**Comment by jmoody** [comment]
I am almost certain that the /device endpoint is not exposed to the Xamarin.UITest client.

**Comment by lukasjuhrich** [comment]
That might be true, but theoretically, I could use the device Endpoint without restricting myself to what Xamarin.UITest exposes by issuing manual http queries. At least a `curl http://127.0.0.1:27753/1.0/device` gives me the complete information.

**Comment by jmoody** [comment]
The embedded Test Cloud Agent `/version` route will provide this information.  I believe there is already an API for the version route.
