### ISSUE TITLE
SpringBoardsAlert doesn't include OAuth alert

### ISSUE THREAD

**Issue by FinHorsley** [calabash/DeviceAgent.iOS#309]
the [SpringBoardsAlert.m](https://github.com/calabash/DeviceAgent.iOS/blob/develop/Server/Utilities/SpringBoardAlerts.m) does not include the OAuth alert text(presented by ASWebAuthenticationSession), and therefore it isn't closed automatically. 

Our app solely uses browser based oauth authentication, so as a result of not being able to close the popup to "continue" with the oauth process, we cannot run automated UI tests with Xamarin.UI
![smiley](https://user-images.githubusercontent.com/10697741/54840234-744cc500-4cc4-11e9-9ccb-9783b6f29e30.png)

**Comment by galfonso777** [comment]
Any plan on adding this request to the DeviceAgent.iOS?

**Comment by jmoody** [comment]
This alert is handled in the latest version of DeviceAgent and the dev versions of Xamarin.UITest.

https://github.com/calabash/DeviceAgent.iOS/blob/develop/Server/Resources.xcassets/springboard-alerts/springboard-alerts-en_GB.dataset/alerts.json#L373

**Comment by jmoody** [comment]
As an aside, there is an API for turning off automatically dismissing SpringBoard alerts.

You can turn off the dismissing and interact with the SpringBoard alerts directly (dismissing with any button).

**Comment by galfonso777** [comment]
Awesome the latest dev version Xamarin.UITest 3.0.4-dev5 worked with no issues. Thank you.
