### ISSUE TITLE
SpringBoardAlerts are missing push notification in swedish.

### ISSUE THREAD

**Issue by marcussogeti** [calabash/DeviceAgent.iOS#357]
We are building an app for the swedish market and are doing automatic ui tests in appcenter. Recently all tests stopped at startup because the alert for push is not dismissed. After some digging it seems the swedish translation for push is missing in alerts.json under assets.

As a workaround we have switched locales to english which seems to be working.

**Comment by Kowah** [comment]
Hi,

We are encountering the same issue for French language ! 

Same hotfix, switched to US on Azure Dev Ops tasks.

**Comment by jmoody** [comment]
Yes.  We have discovered this APNS alert problem.

We are investigating.

**Comment by jmoody** [comment]
run-loop 4.4.2 has been released which fixes this problem.

I am working on starting an Xamarin.UITest releases.

We will be deploying this fix to Test Cloud in the next couple of days.
