### ISSUE TITLE
DeviceAgent-Runner start with custom port.

### ISSUE THREAD

**Issue by donmezburak** [calabash/DeviceAgent.iOS#375]
This is not an issue. I am asking this to get information how to start DeviceAgent-runner. I have to change default 27753 port to custom 27750 port. I cloned repo changed the port and installed DeviceAgent-runner. However http://localhost:27750/... does not give response. I forwarded port using `iproxy` . Still not working.

How can I start deviceagent-runner server on real device in command line ?

Thanks

**Comment by fr0l** [comment]
@donmezburak possibly pull request #373 might help (but it is still work in progress)

**Comment by jmoody** [comment]
Try 127.0.0.1:27750

You need to use `xcodebuild test-without-building [options]` to launch the DeviceAgent.

**Comment by donmezburak** [comment]
> Try 127.0.0.1:27750
> 
> You need to use `xcodebuild test-without-building [options]` to launch the DeviceAgent.

This starts server. When I start to test, it runs and gives

> ** TEST EXECUTE SUCCEEDED **

and closes device agent runner. However my test cases not running. 

> There is no current application

Do i have to change application 

> UITargetAppBundleIdentifier

in xctrestrun file to run my tests ?




> @donmezburak possibly pull request #373 might help (but it is still work in progress)

I checked this but I am asking device-agent-runner and test run relations.

**Comment by donmezburak** [comment]
i fix my problem thank you 🙏
