### ISSUE TITLE
Location permissions dialog title changed

### ISSUE THREAD

**Issue by seanrodda** [calabash/DeviceAgent.iOS#380]
Previously the iOS permissions dialog would say 
"Allow {APP_NAME} to access your location?"

I am using iOS version 13.4 and the dialog title says
"Allow {APP_NAME} to use your location?" as can be seen in the screenshot below, using en GB as the selected language. Running in Visual Studio App Center

Previously calabash would auto accept the dialog. I believe due to the word change, it does not correctly detect the dialog.

![0177751b-9b99-465c-8fbd-9ae3857e148d](https://user-images.githubusercontent.com/4484866/78612508-abc6e900-78a8-11ea-9b6e-b956c662761c.jpeg)

**Comment by jmoody** [comment]
It would be very helpful if someone from the community could fix this.

There are scripts in the repo you can run against Xcode 11.4 that will generate the correct alert titles.

**Comment by seanrodda** [comment]
Ok, no worries. I’ll have a look

**Comment by seanrodda** [comment]
I see that this has now been actioned by Brad Milne yesterday https://github.com/calabash/DeviceAgent.iOS/commit/b9d90bd3c7e73c8f4c5f6a9982028d8d7f305a6d
What is the usual timeframe for when this makes it into a release, or into App Center?

**Comment by jmoody** [comment]
I will start testing in App Center production today.  The Easter holiday will slow down the deployment.  Probably by Tuesday.   I will discuss with my colleague about a Xamarin.UITest dev release.

**Comment by seanrodda** [comment]
No worries. Thanks a lot. Have a great Easter break.

**Comment by lucasholda** [comment]
@jmoody any progress with that?

**Comment by jmoody** [comment]
Sorry.  

A new run-loop was released earlier this week.  

And a new Xamarin.UITest dev release was pushed also.

The fix is waiting to be deployed in Test Cloud.  I am hoping for today, but it looks like it will have to wait for Monday.
